Test missing Github secret env variables

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,7 +5,11 @@ on:
     branches: [main]
   pull_request: 
     branches: [main]
+
   workflow_dispatch:
+
+env:
+  APP_ENV: dev
 
 jobs:
   hello:
@@ -15,6 +19,24 @@ jobs:
         uses: actions/checkout@v4
       - name: Run test command
         run: echo "GitHub Actions is working"
+      - name: Show environment variable
+        run: echo "Environment is $APP_ENV"
+      - name: Show repository
+        run: echo "Repository is $GITHUB_REPOSITORY"    
+      - name: Show commit SHA
+        run: echo "Commit is $GITHUB_SHA"         
+      - name: Show Git ref
+        run: echo "Git ref is $GITHUB_REF" 
+      - name: Use secret
+        env:
+          DEMO_TOKEN: ${{ secrets.DOES_NOT_EXIST }}
+        run:  |
+          if [ -n "$DEMO_TOKEN" ]; then
+            echo "Secret is available"
+          else
+            echo "Secret is missing"
+            exit 1
+          fi 
   test:
     needs: hello
     if: ${{ github.ref == 'refs/heads/main' }}   
